### ISSUE TITLE
compile for android?

### ISSUE THREAD

**Issue by Alekemon** [lufinkey/iSSB#10]
I made Kirby from iSSB Windows and a custom Cuphead into this iSSB. how can I port it to android?

Trying to compile from visual studio on linux and nope

**Comment by lufinkey** [comment]
I think [this](https://lazyfoo.net/tutorials/SDL/52_hello_mobile/android_windows/index.php) should show you how to set it up in android studio. I'd recommend trying to set it up with a fresh branch from this repo instead of your PR though, that way you can make a separate Pull Request for it if you end up getting it working.

For editing this on Linux, I'd recommend using Codelite since my old [GameLibrary](https://github.com/lufinkey/GameLibrary/tree/master/projects/codelite) project has a Codelite project that it uses. You should be able to make a fresh codelite workspace and project and add the GameLibrary project to it as a dependency.

**Comment by Alekemon** [comment]
Thanks! I'll try after college!

**Comment by lufinkey** [comment]
closed since the android studio project is now added
